# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import computer_use_pb2 as computer__use__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in computer_use_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputerUseServiceStub(object):
    """High-level computer-use boundary between Agent X and Machine Y.
    Stable across future ActionType additions; internal actions are NOT exposed here.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputerUse = channel.unary_unary(
                '/computer_use.v1.ComputerUseService/ComputerUse',
                request_serializer=computer__use__pb2.ComputerUseRequest.SerializeToString,
                response_deserializer=computer__use__pb2.ComputerUseResponse.FromString,
                _registered_method=True)


class ComputerUseServiceServicer(object):
    """High-level computer-use boundary between Agent X and Machine Y.
    Stable across future ActionType additions; internal actions are NOT exposed here.

    """

    def ComputerUse(self, request, context):
        """Execute one high-level computer-use task and return a terminal outcome.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputerUseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputerUse': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputerUse,
                    request_deserializer=computer__use__pb2.ComputerUseRequest.FromString,
                    response_serializer=computer__use__pb2.ComputerUseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computer_use.v1.ComputerUseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('computer_use.v1.ComputerUseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputerUseService(object):
    """High-level computer-use boundary between Agent X and Machine Y.
    Stable across future ActionType additions; internal actions are NOT exposed here.

    """

    @staticmethod
    def ComputerUse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computer_use.v1.ComputerUseService/ComputerUse',
            computer__use__pb2.ComputerUseRequest.SerializeToString,
            computer__use__pb2.ComputerUseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
