# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: computer_use.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'computer_use.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omputer_use.proto\x12\x0f\x63omputer_use.v1\"\xc6\x01\n\x12\x43omputerUseRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x01(\t\x12\x14\n\x0c\x63onversation\x18\x03 \x01(\t\x12\x41\n\x07\x63ontext\x18\x04 \x03(\x0b\x32\x30.computer_use.v1.ComputerUseRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa7\x01\n\x13\x43omputerUseResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x31\n\x0bobservation\x18\x04 \x01(\x0b\x32\x1c.computer_use.v1.Observation\x12)\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x1a.computer_use.v1.ErrorInfo\"Q\n\x0bObservation\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"*\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2n\n\x12\x43omputerUseService\x12X\n\x0b\x43omputerUse\x12#.computer_use.v1.ComputerUseRequest\x1a$.computer_use.v1.ComputerUseResponseB\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'computer_use_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_COMPUTERUSEREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_COMPUTERUSEREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_COMPUTERUSEREQUEST']._serialized_start=40
  _globals['_COMPUTERUSEREQUEST']._serialized_end=238
  _globals['_COMPUTERUSEREQUEST_CONTEXTENTRY']._serialized_start=192
  _globals['_COMPUTERUSEREQUEST_CONTEXTENTRY']._serialized_end=238
  _globals['_COMPUTERUSERESPONSE']._serialized_start=241
  _globals['_COMPUTERUSERESPONSE']._serialized_end=408
  _globals['_OBSERVATION']._serialized_start=410
  _globals['_OBSERVATION']._serialized_end=491
  _globals['_ERRORINFO']._serialized_start=493
  _globals['_ERRORINFO']._serialized_end=535
  _globals['_COMPUTERUSESERVICE']._serialized_start=537
  _globals['_COMPUTERUSESERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
